INSERT INTO `questions`(`test_id`, `question_text`, `option_1`, `option_2`, `option_3`, `correct_option`) VALUES 
('geds203-1','___ pomme est rouge.','Le','Un','Des','La'),
('geds203-1','Elle ___ au marché chaque matin.','a','est','fait','va'),
('geds203-1','Je ___ deux frères.','suis','vais','fais','ai'),
('geds203-1','Ils ___ fatigués après le travail.','ont','vont','ont eu','sont'),
('geds203-1','Nous ___ à l’école.','sommes','avons','faisons','allons'),
('geds203-1','Choisis l’article correct : ___ stylo.','La','Une','Des','Le'),
('geds203-1','Tu ___ un bon ami.','vas','as','fais','es'),
('geds203-1','Quel est le mot français pour "head"?','main','pied','ventre','tête'),
('geds203-1','Comment dit-on "school" en français ?','maison','travail','église','école'),
('geds203-1','___ chat est noir.','Une','Les','Un','Le'),
('geds203-1','Elle ___ les escaliers lentement.','descend','descends','descendent','descend'),
('geds203-1','Nous ___ à la bibliothèque demain.','sommes','avons','faisons','allons'),
('geds203-1','Il ___ trois crayons.','va','est','fait','a'),
('geds203-1','Quelle heure est-il ? Il est ___ heures.','vingt','demain','midi','trois'),
('geds203-1','Je ___ mon livre sur la table.','est','fais','vais','mets'),
('geds203-1','Ils ___ au cinéma samedi.','sont','ont','font','vont'),
('geds203-1','Je ___ très content aujourd’hui.','ai','vais','fais','suis'),
('geds203-1','Choisis le bon article : ___ horloge','Le','Un','Des','La'),
('geds203-1','Elle ___ une jupe rouge.','va','est','fait','porte'),
('geds203-1','Nous ___ français et espagnol.','sommes','allons','avons','parlons'),
('geds203-1','Tu ___ une chanson ?','est','es','vas','chantes'),
('geds203-1','Je ___ au marché tous les jours.','es','a','fait','vais'),
('geds203-1','Le mot "chien" signifie :','cat','rabbit','bird','dog'),
('geds203-1','How do you say "I have a pen" in French?','J’ai un crayon','Je suis un stylo','Je vais un crayon','J’ai un stylo'),
('geds203-1','___ voiture est rapide.','Le','Un','Des','La'),
('geds203-1','Ils ___ leurs devoirs maintenant.','vont','ont','sont','font'),
('geds203-1','Tu ___ très drôle !','as','vas','fais','es'),
('geds203-1','"Main" in English is:','Head','Leg','Foot','Hand'),
('geds203-1','Je ___ mes devoirs après le dîner.','suis','ai','vais','fais'),
('geds203-1','Il ___ tard.','a','fait','va','est'),
('geds203-1','Choisis le bon article : ___ arbre.','La','Une','Des','L’'),
('geds203-1','Vous ___ gentils.','avez','faites','allez','êtes'),
('geds203-1','Nous ___ souvent du sport le samedi.','sommes','allons','avons','faisons'),
('geds203-1','Elle ___ une robe bleue.','es','est','vas','porte'),
('geds203-1','Je ___ une table rouge.','suis','vais','fais','vois'),
('geds203-1','Tu ___ au marché le matin.','es','fais','as','vas'),
('geds203-1','Ils ___ leurs sacs dans la voiture.','sont','ont','vont','mettent'),
('geds203-1','Il ___ six heures.','fait','va','suis','est'),
('geds203-1','Le mot "jambe" signifie :','hand','ear','foot','leg'),
('geds203-1','Je ___ fatigué après l’école.','vais','fais','ai','suis'),
('geds203-1','___ enfants jouent dans le parc.','Le','Un','La','Les'),
('geds203-1','Elle ___ ses devoirs.','es','a','vas','fait'),
('geds203-1','Nous ___ à Paris cet été.','sommes','faisons','avons','allons'),
('geds203-1','"Oreille" in English is:','eye','nose','mouth','ear'),
('geds203-1','Tu ___ un bon repas.','es','vas','as','prépares'),
('geds203-1','___ éléphant est grand.','Le','Un','Une','Des'),
('geds203-1','Vous ___ à l’heure.','avez','faites','allez','êtes'),
('geds203-1','Il ___ dans la piscine.','es','fais','est','nage'),
('geds203-1','How do you say "We are happy" in French?','Nous faisons content','Nous allons content','Nous avons content','Nous sommes contents');
